version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 10

volumes:
  localstack_data: